# Serverless deployment configuration for Support Wheel of Fate
service: swof-api

# Custom variables
custom:
  tableName: 'developers-table-${self:provider.stage}'

# Provider definition
# We use AWS Lambda for our computational needs
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["DevelopersDynamoDBTable", "Arn" ] }
  environment:
    DEVELOPERS_TABLE: ${self:custom.tableName}

# Lambda functions
functions:
  swof:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

# CloudFormation resource templates
resources:
  Resources:
    DevelopersDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: developerId
            AttributeType: S
        KeySchema:
          -
            AttributeName: developerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}